Repository codeBeamer-Extensions-and-Addons/codebeamer-miro, pull requests merged in 2023-05, with the labels that each got.

#100 Increase max number of Items that can be synched / updated
  package-lock.json
  package.json
  src/pages/import/components/updater/Updater.tsx
Labels: bug

#95 Dependency association visualization Implementation
  cypress/fixtures/itemRelationsForRelationsButton.json
  package-lock.json
  package.json
  src/api/codeBeamerApi.ts
  src/api/miro.api.ts
  src/api/utils/doAllConnectorsExist.ts
  src/api/utils/doesConnectorExist.ts
  src/api/utils/getAppCardIds.ts
  src/api/utils/getColorForRelationshipType.ts
  src/api/utils/removeConnectors.ts
  src/assets/style.css
  src/enums/associationRelationshipType.enum.ts
  src/hooks/useItemRelations.ts
  src/index.ts
  src/models/api-query-types.ts
  src/models/relation.if.ts
  src/pages/item/item-actions/ItemActions.tsx
  src/pages/item/item-actions/itemActions.cy.tsx
  src/pages/item/item-actions/itemActionsButtons/loadDownstreamReferencesButton/loadDownStreamReferencesButton.cy.tsx
  src/pages/item/item-actions/itemActionsButtons/loadDownstreamReferencesButton/loadDownstreamReferencesButton.tsx
  src/pages/item/item-actions/itemActionsButtons/loadRelationsButton/loadRelationsButton.cy.tsx
  src/pages/item/item-actions/itemActionsButtons/loadRelationsButton/loadRelationsButton.tsx
  src/pages/item/item-actions/itemActionsButtons/zoomToItemButton/ZoomToItemButton.tsx
  src/pages/item/item-actions/itemActionsButtons/zoomToItemButton/zoomToItemButton.cy.tsx
  src/pages/item/itemDetails.tsx
  src/pages/item/itemSummary/ItemSummary.tsx
  src/pages/item/itemSummary/itemSummary.cy.tsx
  vite.config.js
Labels: enhancement

#103 Add "ID" default / hardcoded filter
  src/enums/default-filter-criteria.enum.ts
  src/pages/import/components/query/filterInput/FilterInput.tsx
  src/store/util/getQueryEntityNameForCriteria.ts
Labels: enhancement

#102 Fetch Tracker Key per Item instead of per Import
  cypress/fixtures/query_diff_trackers.json
  package-lock.json
  src/api/miro.api.ts
  src/pages/import/components/importer/Importer.tsx
  src/pages/import/components/importer/importer.cy.tsx
  src/pages/import/components/settings/cardCustomization/appCardTagSettings.cy.tsx
Labels: bug

#104 Add tooltips on Import page
  package.json
  src/pages/import/components/importHeader/ImportHeader.tsx
  src/pages/import/components/importHeader/importHeader.css
Labels: enhancement

#106 Release/1.5 -> develop
  CHANGELOG.md
  README.md
  index.html
  package.json
  readmeImg/connectors.gif
  src/index.ts
  src/pages/announcements/Announcements.tsx
Labels: release
